Vertauschtes bild
jstriebel/webcam-effects pull request #6
Opened 2017-08-07 16:10 UTC by luchtele

2017-08-07 20:22 UTC, lucaschimweg requested changes

2017-08-07 20:22 UTC, lucaschimweg commented on pipes/negativ_pipe.py
> +        whiteframe = np.ones(img.shape, sdtype=np.uint8) * 255
I get an error executing the filter here: I think you mean `dtype=np.uint8` instead of `sdtype=np.uint8`

2017-08-09 20:46 UTC, normanrz commented
@lucaschimweg can you check again?

2017-08-12 16:34 UTC, lucaschimweg approved these changes

2017-08-12 16:35 UTC, merged

2017-08-12 16:35 UTC, lucaschimweg commented
Merged it, nice work!